name: build-mcp-image
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Make a lowercase copy of the owner name
      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Build & push using the lowercase owner
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/twelvedata-mcp:latest
